#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-resources-plugin
Version  : 2.7
Release  : 1
URL      : https://github.com/apache/maven-resources-plugin/archive/maven-resources-plugin-2.7.tar.gz
Source0  : https://github.com/apache/maven-resources-plugin/archive/maven-resources-plugin-2.7.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
